### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by marcin-wosinek** [snakemode/snowpack-html-loader-plugin#1]
hello. I found this project while searching for something similar to `html-loader` from webpack. I'm not sure if it's a good match for my usecase since there is no documentation. If you want some broader adoption of this code, at least few lines about setting it up in a readme would help. All the best!

**Comment by davidwhitney** [comment]
Hey!

This is currently "paint-dripping-wet-new" built for something we're currently working on.

Due to the way snowpack plugins work, you pretty much have to publish them to be able to consume them, even in your own stuff. But yes, there will be documentation, I'll try scratch something together.

**Comment by davidwhitney** [comment]
Added basic docs.
